### ISSUE TITLE
Please respect the standard BUILD_SHARED_LIBS cmake variable

### ISSUE THREAD

**Issue by yurivict** [iurienistor/redkite#32]
This line forces static library: https://github.com/iurienistor/redkite/blob/master/CMakeLists.txt#L177

Shared libraries are normally triggered depend by ```BUILD_SHARED_LIBS```, see here https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html

Could you please make the project use ```BUILD_SHARED_LIBS```?

Thank you!
Yuri

**Comment by iurienistor** [comment]
Hi! The central idea behind this small GUI toolkit is to enable developing self-sufficient GUI plugins that are loaded by the applications in their address space. Static linking against Redkite it must make Redkite invisible between application and X11 API, no additional shared libraries related to toolkit, only those provided by the operating system. Thus, it is not expected this Redkite library to be acutally shipped for run-time purposes, i.e. as shared library, only for development as static library.
